common: &every_env
  visualization:
    images:
      mtype: png
      dir: /images
  allow_duplicate_hostname: false
  report:
    email:
      from: unix-sa@example.com
      to: unix-sa@example.com
  notifications:
    status_update: true
    
development: &non_production_env
  <<: *every_env
  redirect_login_to_ssl: false
  
test:
  <<: *non_production_env

production:
  <<: *every_env
  redirect_login_to_ssl: true
