# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 30) do

  create_table "account_versions", :force => true do |t|
    t.column "account_id",    :integer
    t.column "version",       :integer
    t.column "name",          :string
    t.column "login",         :string
    t.column "password_hash", :string
    t.column "password_salt", :string
    t.column "email_address", :string
    t.column "admin",         :boolean,  :default => false
    t.column "created_at",    :datetime
    t.column "updated_at",    :datetime
    t.column "deleted_at",    :datetime
  end

  create_table "accounts", :force => true do |t|
    t.column "name",          :string
    t.column "login",         :string
    t.column "password_hash", :string
    t.column "password_salt", :string
    t.column "email_address", :string
    t.column "admin",         :boolean,  :default => false
    t.column "created_at",    :datetime
    t.column "updated_at",    :datetime
    t.column "deleted_at",    :datetime
    t.column "version",       :integer
  end

  add_index "accounts", ["id"], :name => "index_accounts_on_id"
  add_index "accounts", ["name"], :name => "index_accounts_on_name"
  add_index "accounts", ["deleted_at"], :name => "index_accounts_on_deleted_at"

  create_table "customer_versions", :force => true do |t|
    t.column "customer_id", :integer
    t.column "version",     :integer
    t.column "name",        :string
    t.column "notes",       :text
    t.column "created_at",  :datetime
    t.column "updated_at",  :datetime
    t.column "deleted_at",  :datetime
  end

  create_table "customers", :force => true do |t|
    t.column "name",       :string
    t.column "notes",      :text
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "deleted_at", :datetime
    t.column "version",    :integer
  end

  add_index "customers", ["id"], :name => "index_customers_on_id"
  add_index "customers", ["name"], :name => "index_customers_on_name"
  add_index "customers", ["deleted_at"], :name => "index_customers_on_deleted_at"

  create_table "database_instance_relationship_versions", :force => true do |t|
    t.column "database_instance_relationship_id", :integer
    t.column "version",                           :integer
    t.column "name",                              :string
    t.column "from_id",                           :integer
    t.column "to_id",                             :integer
    t.column "assigned_at",                       :datetime
    t.column "created_at",                        :datetime
    t.column "updated_at",                        :datetime
    t.column "deleted_at",                        :datetime
  end

  create_table "database_instance_relationships", :force => true do |t|
    t.column "name",        :string
    t.column "from_id",     :integer
    t.column "to_id",       :integer
    t.column "assigned_at", :datetime
    t.column "created_at",  :datetime
    t.column "updated_at",  :datetime
    t.column "deleted_at",  :datetime
    t.column "version",     :integer
  end

  add_index "database_instance_relationships", ["id"], :name => "index_database_instance_relationships_on_id"
  add_index "database_instance_relationships", ["name"], :name => "index_database_instance_relationships_on_name"
  add_index "database_instance_relationships", ["from_id"], :name => "index_database_instance_relationships_on_from_id"
  add_index "database_instance_relationships", ["to_id"], :name => "index_database_instance_relationships_on_to_id"
  add_index "database_instance_relationships", ["assigned_at"], :name => "index_database_instance_relationships_on_assigned_at"
  add_index "database_instance_relationships", ["deleted_at"], :name => "index_database_instance_relationships_on_deleted_at"

  create_table "database_instance_versions", :force => true do |t|
    t.column "database_instance_id", :integer
    t.column "version",              :integer
    t.column "name",                 :string
    t.column "notes",                :text
    t.column "created_at",           :datetime
    t.column "updated_at",           :datetime
    t.column "deleted_at",           :datetime
  end

  create_table "database_instances", :force => true do |t|
    t.column "name",       :string
    t.column "notes",      :text
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "deleted_at", :datetime
    t.column "version",    :integer
  end

  add_index "database_instances", ["id"], :name => "index_database_instances_on_id"
  add_index "database_instances", ["name"], :name => "index_database_instances_on_name"
  add_index "database_instances", ["deleted_at"], :name => "index_database_instances_on_deleted_at"

  create_table "datacenter_environment_assignment_versions", :force => true do |t|
    t.column "datacenter_environment_assignment_id", :integer
    t.column "version",                              :integer
    t.column "datacenter_id",                        :integer
    t.column "environment_id",                       :integer
    t.column "assigned_at",                          :datetime
    t.column "created_at",                           :datetime
    t.column "updated_at",                           :datetime
    t.column "deleted_at",                           :datetime
  end

  create_table "datacenter_environment_assignments", :force => true do |t|
    t.column "datacenter_id",  :integer
    t.column "environment_id", :integer
    t.column "assigned_at",    :datetime
    t.column "created_at",     :datetime
    t.column "updated_at",     :datetime
    t.column "deleted_at",     :datetime
    t.column "version",        :integer
  end

  add_index "datacenter_environment_assignments", ["id"], :name => "index_datacenter_environment_assignments_on_id"
  add_index "datacenter_environment_assignments", ["datacenter_id"], :name => "index_datacenter_environment_assignments_on_datacenter_id"
  add_index "datacenter_environment_assignments", ["environment_id"], :name => "index_datacenter_environment_assignments_on_environment_id"
  add_index "datacenter_environment_assignments", ["assigned_at"], :name => "index_datacenter_environment_assignments_on_assigned_at"
  add_index "datacenter_environment_assignments", ["deleted_at"], :name => "index_datacenter_environment_assignments_on_deleted_at"

  create_table "datacenter_rack_assignment_versions", :force => true do |t|
    t.column "datacenter_rack_assignment_id", :integer
    t.column "version",                       :integer
    t.column "datacenter_id",                 :integer
    t.column "rack_id",                       :integer
    t.column "assigned_at",                   :datetime
    t.column "created_at",                    :datetime
    t.column "updated_at",                    :datetime
    t.column "deleted_at",                    :datetime
  end

  create_table "datacenter_rack_assignments", :force => true do |t|
    t.column "datacenter_id", :integer
    t.column "rack_id",       :integer
    t.column "assigned_at",   :datetime
    t.column "created_at",    :datetime
    t.column "updated_at",    :datetime
    t.column "deleted_at",    :datetime
    t.column "version",       :integer
  end

  add_index "datacenter_rack_assignments", ["id"], :name => "index_datacenter_rack_assignments_on_id"
  add_index "datacenter_rack_assignments", ["datacenter_id"], :name => "index_datacenter_rack_assignments_on_datacenter_id"
  add_index "datacenter_rack_assignments", ["rack_id"], :name => "index_datacenter_rack_assignments_on_rack_id"
  add_index "datacenter_rack_assignments", ["assigned_at"], :name => "index_datacenter_rack_assignments_on_assigned_at"
  add_index "datacenter_rack_assignments", ["deleted_at"], :name => "index_datacenter_rack_assignments_on_deleted_at"

  create_table "datacenter_versions", :force => true do |t|
    t.column "datacenter_id",        :integer
    t.column "version",              :integer
    t.column "name",                 :string
    t.column "physical_address",     :text
    t.column "shipping_address",     :text
    t.column "manager",              :string
    t.column "support_phone_number", :string
    t.column "support_email",        :string
    t.column "support_url",          :string
    t.column "created_at",           :datetime
    t.column "updated_at",           :datetime
    t.column "deleted_at",           :datetime
  end

  create_table "datacenters", :force => true do |t|
    t.column "name",                 :string
    t.column "physical_address",     :text
    t.column "shipping_address",     :text
    t.column "manager",              :string
    t.column "support_phone_number", :string
    t.column "support_email",        :string
    t.column "support_url",          :string
    t.column "created_at",           :datetime
    t.column "updated_at",           :datetime
    t.column "deleted_at",           :datetime
    t.column "version",              :integer
  end

  add_index "datacenters", ["id"], :name => "index_datacenters_on_id"
  add_index "datacenters", ["name"], :name => "index_datacenters_on_name"
  add_index "datacenters", ["deleted_at"], :name => "index_datacenters_on_deleted_at"

  create_table "environment_node_assignment_versions", :force => true do |t|
    t.column "environment_node_assignment_id", :integer
    t.column "version",                        :integer
    t.column "environment_id",                 :integer
    t.column "node_id",                        :integer
    t.column "assigned_at",                    :datetime
    t.column "created_at",                     :datetime
    t.column "updated_at",                     :datetime
    t.column "deleted_at",                     :datetime
  end

  create_table "environment_node_assignments", :force => true do |t|
    t.column "environment_id", :integer
    t.column "node_id",        :integer
    t.column "assigned_at",    :datetime
    t.column "created_at",     :datetime
    t.column "updated_at",     :datetime
    t.column "deleted_at",     :datetime
    t.column "version",        :integer
  end

  add_index "environment_node_assignments", ["id"], :name => "index_environment_node_assignments_on_id"
  add_index "environment_node_assignments", ["node_id"], :name => "index_environment_node_assignments_on_node_id"
  add_index "environment_node_assignments", ["environment_id"], :name => "index_environment_node_assignments_on_environment_id"
  add_index "environment_node_assignments", ["assigned_at"], :name => "index_environment_node_assignments_on_assigned_at"
  add_index "environment_node_assignments", ["deleted_at"], :name => "index_environment_node_assignments_on_deleted_at"

  create_table "environment_program_assignment_versions", :force => true do |t|
    t.column "environment_program_assignment_id", :integer
    t.column "version",                           :integer
    t.column "environment_id",                    :integer
    t.column "program_id",                        :integer
    t.column "assigned_at",                       :datetime
    t.column "created_at",                        :datetime
    t.column "updated_at",                        :datetime
    t.column "deleted_at",                        :datetime
  end

  create_table "environment_program_assignments", :force => true do |t|
    t.column "environment_id", :integer
    t.column "program_id",     :integer
    t.column "assigned_at",    :datetime
    t.column "created_at",     :datetime
    t.column "updated_at",     :datetime
    t.column "deleted_at",     :datetime
    t.column "version",        :integer
  end

  add_index "environment_program_assignments", ["id"], :name => "index_environment_program_assignments_on_id"
  add_index "environment_program_assignments", ["program_id"], :name => "index_environment_program_assignments_on_program_id"
  add_index "environment_program_assignments", ["environment_id"], :name => "index_environment_program_assignments_on_environment_id"
  add_index "environment_program_assignments", ["assigned_at"], :name => "index_environment_program_assignments_on_assigned_at"
  add_index "environment_program_assignments", ["deleted_at"], :name => "index_environment_program_assignments_on_deleted_at"

  create_table "environment_versions", :force => true do |t|
    t.column "environment_id", :integer
    t.column "version",        :integer
    t.column "name",           :string
    t.column "notes",          :text
    t.column "created_at",     :datetime
    t.column "updated_at",     :datetime
    t.column "deleted_at",     :datetime
  end

  create_table "environments", :force => true do |t|
    t.column "name",       :string
    t.column "notes",      :text
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "deleted_at", :datetime
    t.column "version",    :integer
  end

  add_index "environments", ["id"], :name => "index_environments_on_id"
  add_index "environments", ["name"], :name => "index_environments_on_name"
  add_index "environments", ["deleted_at"], :name => "index_environments_on_deleted_at"

  create_table "function_type_versions", :force => true do |t|
    t.column "function_type_id",                 :integer
    t.column "version",                          :integer
    t.column "name",                             :string
    t.column "notes",                            :text
    t.column "enables_database_instance_access", :boolean,  :default => false
    t.column "created_at",                       :datetime
    t.column "updated_at",                       :datetime
    t.column "deleted_at",                       :datetime
  end

  create_table "function_types", :force => true do |t|
    t.column "name",                             :string
    t.column "notes",                            :text
    t.column "enables_database_instance_access", :boolean,  :default => false
    t.column "created_at",                       :datetime
    t.column "updated_at",                       :datetime
    t.column "deleted_at",                       :datetime
    t.column "version",                          :integer
  end

  add_index "function_types", ["id"], :name => "index_function_types_on_id"
  add_index "function_types", ["name"], :name => "index_function_types_on_name"
  add_index "function_types", ["deleted_at"], :name => "index_function_types_on_deleted_at"

  create_table "function_versions", :force => true do |t|
    t.column "function_id",      :integer
    t.column "version",          :integer
    t.column "name",             :string
    t.column "function_type_id", :integer
    t.column "notes",            :text
    t.column "created_at",       :datetime
    t.column "updated_at",       :datetime
    t.column "deleted_at",       :datetime
  end

  create_table "functions", :force => true do |t|
    t.column "name",             :string
    t.column "function_type_id", :integer
    t.column "notes",            :text
    t.column "created_at",       :datetime
    t.column "updated_at",       :datetime
    t.column "deleted_at",       :datetime
    t.column "version",          :integer
  end

  add_index "functions", ["id"], :name => "index_functions_on_id"
  add_index "functions", ["name"], :name => "index_functions_on_name"
  add_index "functions", ["deleted_at"], :name => "index_functions_on_deleted_at"
  add_index "functions", ["function_type_id"], :name => "index_functions_on_function_type_id"

  create_table "hardware_profile_versions", :force => true do |t|
    t.column "hardware_profile_id", :integer
    t.column "version",             :integer
    t.column "name",                :string
    t.column "manufacturer",        :string
    t.column "rack_size",           :integer,  :default => 1
    t.column "memory",              :string
    t.column "disk",                :string
    t.column "nics",                :integer,  :default => 0
    t.column "processor_type",      :string
    t.column "processor_speed",     :string
    t.column "processor_count",     :integer,  :default => 0
    t.column "cards",               :string
    t.column "notes",               :text
    t.column "outlet_count",        :integer,  :default => 0
    t.column "estimated_cost",      :integer,  :default => 0
    t.column "created_at",          :datetime
    t.column "updated_at",          :datetime
    t.column "deleted_at",          :datetime
    t.column "visualization_color", :string,   :default => "red"
    t.column "outlet_type",         :string
    t.column "power_supply_count",  :integer,  :default => 0
  end

  create_table "hardware_profiles", :force => true do |t|
    t.column "name",                :string
    t.column "manufacturer",        :string
    t.column "rack_size",           :integer,  :default => 1
    t.column "memory",              :string
    t.column "disk",                :string
    t.column "nics",                :integer,  :default => 0
    t.column "processor_type",      :string
    t.column "processor_speed",     :string
    t.column "processor_count",     :integer,  :default => 0
    t.column "cards",               :string
    t.column "notes",               :text
    t.column "outlet_count",        :integer,  :default => 0
    t.column "estimated_cost",      :integer,  :default => 0
    t.column "created_at",          :datetime
    t.column "updated_at",          :datetime
    t.column "deleted_at",          :datetime
    t.column "version",             :integer
    t.column "visualization_color", :string,   :default => "red"
    t.column "outlet_type",         :string
    t.column "power_supply_count",  :integer,  :default => 0
  end

  add_index "hardware_profiles", ["id"], :name => "index_hardware_profiles_on_id"
  add_index "hardware_profiles", ["name"], :name => "index_hardware_profiles_on_name"
  add_index "hardware_profiles", ["deleted_at"], :name => "index_hardware_profiles_on_deleted_at"

  create_table "node_database_instance_assignment_versions", :force => true do |t|
    t.column "node_database_instance_assignment_id", :integer
    t.column "version",                              :integer
    t.column "node_id",                              :integer
    t.column "database_instance_id",                 :integer
    t.column "assigned_at",                          :datetime
    t.column "created_at",                           :datetime
    t.column "updated_at",                           :datetime
    t.column "deleted_at",                           :datetime
  end

  create_table "node_database_instance_assignments", :force => true do |t|
    t.column "node_id",              :integer
    t.column "database_instance_id", :integer
    t.column "assigned_at",          :datetime
    t.column "created_at",           :datetime
    t.column "updated_at",           :datetime
    t.column "deleted_at",           :datetime
    t.column "version",              :integer
  end

  add_index "node_database_instance_assignments", ["id"], :name => "index_node_database_instance_assignments_on_id"
  add_index "node_database_instance_assignments", ["node_id"], :name => "index_node_database_instance_assignments_on_node_id"
  add_index "node_database_instance_assignments", ["database_instance_id"], :name => "index_node_database_instance_assignments_on_database_instance_id"
  add_index "node_database_instance_assignments", ["assigned_at"], :name => "index_node_database_instance_assignments_on_assigned_at"
  add_index "node_database_instance_assignments", ["deleted_at"], :name => "index_node_database_instance_assignments_on_deleted_at"

  create_table "node_function_assignment_versions", :force => true do |t|
    t.column "node_function_assignment_id", :integer
    t.column "version",                     :integer
    t.column "node_id",                     :integer
    t.column "function_id",                 :integer
    t.column "assigned_at",                 :datetime
    t.column "created_at",                  :datetime
    t.column "updated_at",                  :datetime
    t.column "deleted_at",                  :datetime
  end

  create_table "node_function_assignments", :force => true do |t|
    t.column "node_id",     :integer
    t.column "function_id", :integer
    t.column "assigned_at", :datetime
    t.column "created_at",  :datetime
    t.column "updated_at",  :datetime
    t.column "deleted_at",  :datetime
    t.column "version",     :integer
  end

  add_index "node_function_assignments", ["id"], :name => "index_node_function_assignments_on_id"
  add_index "node_function_assignments", ["node_id"], :name => "index_node_function_assignments_on_node_id"
  add_index "node_function_assignments", ["function_id"], :name => "index_node_function_assignments_on_function_id"
  add_index "node_function_assignments", ["assigned_at"], :name => "index_node_function_assignments_on_assigned_at"
  add_index "node_function_assignments", ["deleted_at"], :name => "index_node_function_assignments_on_deleted_at"

  create_table "node_versions", :force => true do |t|
    t.column "node_id",             :integer
    t.column "version",             :integer
    t.column "name",                :string
    t.column "serial_number",       :string
    t.column "created_at",          :datetime
    t.column "updated_at",          :datetime
    t.column "deleted_at",          :datetime
    t.column "hardware_profile_id", :integer
    t.column "operating_system_id", :integer
    t.column "ipaddresses",         :text
    t.column "status_id",           :integer
  end

  create_table "nodes", :force => true do |t|
    t.column "name",                :string
    t.column "serial_number",       :string
    t.column "created_at",          :datetime
    t.column "updated_at",          :datetime
    t.column "deleted_at",          :datetime
    t.column "version",             :integer
    t.column "hardware_profile_id", :integer
    t.column "operating_system_id", :integer
    t.column "ipaddresses",         :text
    t.column "status_id",           :integer
  end

  add_index "nodes", ["id"], :name => "index_nodes_on_id"
  add_index "nodes", ["name"], :name => "index_nodes_on_name"
  add_index "nodes", ["serial_number"], :name => "index_nodes_on_serial_number"
  add_index "nodes", ["deleted_at"], :name => "index_nodes_on_deleted_at"
  add_index "nodes", ["hardware_profile_id"], :name => "index_nodes_on_hardware_profile_id"
  add_index "nodes", ["status_id"], :name => "index_nodes_on_status_id"

  create_table "operating_system_versions", :force => true do |t|
    t.column "operating_system_id", :integer
    t.column "version",             :integer
    t.column "name",                :string
    t.column "vendor",              :string
    t.column "variant",             :string
    t.column "version_number",      :string
    t.column "created_at",          :datetime
    t.column "updated_at",          :datetime
    t.column "deleted_at",          :datetime
  end

  create_table "operating_systems", :force => true do |t|
    t.column "name",           :string
    t.column "vendor",         :string
    t.column "variant",        :string
    t.column "version_number", :string
    t.column "created_at",     :datetime
    t.column "updated_at",     :datetime
    t.column "deleted_at",     :datetime
    t.column "version",        :integer
  end

  add_index "operating_systems", ["id"], :name => "index_operating_systems_on_id"
  add_index "operating_systems", ["name"], :name => "index_operating_systems_on_name"
  add_index "operating_systems", ["deleted_at"], :name => "index_operating_systems_on_deleted_at"

  create_table "outlet_versions", :force => true do |t|
    t.column "outlet_id",   :integer
    t.column "version",     :integer
    t.column "name",        :string
    t.column "producer_id", :integer
    t.column "consumer_id", :integer
    t.column "created_at",  :datetime
    t.column "updated_at",  :datetime
    t.column "deleted_at",  :datetime
  end

  create_table "outlets", :force => true do |t|
    t.column "name",        :string
    t.column "producer_id", :integer
    t.column "consumer_id", :integer
    t.column "created_at",  :datetime
    t.column "updated_at",  :datetime
    t.column "deleted_at",  :datetime
    t.column "version",     :integer
  end

  add_index "outlets", ["id"], :name => "index_outlets_on_id"
  add_index "outlets", ["name"], :name => "index_outlets_on_name"
  add_index "outlets", ["producer_id"], :name => "index_outlets_on_producer_id"
  add_index "outlets", ["consumer_id"], :name => "index_outlets_on_consumer_id"
  add_index "outlets", ["deleted_at"], :name => "index_outlets_on_deleted_at"

  create_table "program_versions", :force => true do |t|
    t.column "program_id",    :integer
    t.column "version",       :integer
    t.column "customer_id",   :integer
    t.column "status_id",     :integer
    t.column "name",          :string
    t.column "notes",         :text
    t.column "main_url",      :string
    t.column "stream_url",    :string
    t.column "analytics_url", :string
    t.column "reporting_url", :string
    t.column "created_at",    :datetime
    t.column "updated_at",    :datetime
    t.column "deleted_at",    :datetime
  end

  create_table "programs", :force => true do |t|
    t.column "customer_id",   :integer
    t.column "status_id",     :integer
    t.column "name",          :string
    t.column "notes",         :text
    t.column "main_url",      :string
    t.column "stream_url",    :string
    t.column "analytics_url", :string
    t.column "reporting_url", :string
    t.column "created_at",    :datetime
    t.column "updated_at",    :datetime
    t.column "deleted_at",    :datetime
    t.column "version",       :integer
  end

  add_index "programs", ["id"], :name => "index_programs_on_id"
  add_index "programs", ["customer_id"], :name => "index_programs_on_customer_id"
  add_index "programs", ["status_id"], :name => "index_programs_on_status_id"
  add_index "programs", ["name"], :name => "index_programs_on_name"
  add_index "programs", ["deleted_at"], :name => "index_programs_on_deleted_at"

  create_table "rack_node_assignment_versions", :force => true do |t|
    t.column "rack_node_assignment_id", :integer
    t.column "version",                 :integer
    t.column "rack_id",                 :integer
    t.column "node_id",                 :integer
    t.column "position",                :integer
    t.column "assigned_at",             :datetime
    t.column "created_at",              :datetime
    t.column "updated_at",              :datetime
    t.column "deleted_at",              :datetime
  end

  create_table "rack_node_assignments", :force => true do |t|
    t.column "rack_id",     :integer
    t.column "node_id",     :integer
    t.column "position",    :integer
    t.column "assigned_at", :datetime
    t.column "created_at",  :datetime
    t.column "updated_at",  :datetime
    t.column "deleted_at",  :datetime
    t.column "version",     :integer
  end

  add_index "rack_node_assignments", ["id"], :name => "index_rack_node_assignments_on_id"
  add_index "rack_node_assignments", ["node_id"], :name => "index_rack_node_assignments_on_node_id"
  add_index "rack_node_assignments", ["rack_id"], :name => "index_rack_node_assignments_on_rack_id"
  add_index "rack_node_assignments", ["assigned_at"], :name => "index_rack_node_assignments_on_assigned_at"
  add_index "rack_node_assignments", ["deleted_at"], :name => "index_rack_node_assignments_on_deleted_at"

  create_table "rack_versions", :force => true do |t|
    t.column "rack_id",    :integer
    t.column "version",    :integer
    t.column "name",       :string
    t.column "location",   :text
    t.column "notes",      :text
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "deleted_at", :datetime
  end

  create_table "racks", :force => true do |t|
    t.column "name",       :string
    t.column "location",   :text
    t.column "notes",      :text
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "deleted_at", :datetime
    t.column "version",    :integer
  end

  add_index "racks", ["id"], :name => "index_racks_on_id"
  add_index "racks", ["name"], :name => "index_racks_on_name"
  add_index "racks", ["deleted_at"], :name => "index_racks_on_deleted_at"

  create_table "status_versions", :force => true do |t|
    t.column "status_id",      :integer
    t.column "version",        :integer
    t.column "name",           :string
    t.column "notes",          :text
    t.column "created_at",     :datetime
    t.column "updated_at",     :datetime
    t.column "deleted_at",     :datetime
    t.column "relevant_model", :string
  end

  create_table "statuses", :force => true do |t|
    t.column "name",           :string
    t.column "notes",          :text
    t.column "created_at",     :datetime
    t.column "updated_at",     :datetime
    t.column "deleted_at",     :datetime
    t.column "version",        :integer
    t.column "relevant_model", :string
  end

  add_index "statuses", ["id"], :name => "index_statuses_on_id"
  add_index "statuses", ["name"], :name => "index_statuses_on_name"
  add_index "statuses", ["deleted_at"], :name => "index_statuses_on_deleted_at"

end
